import {
  Box,
  Typography,
  Container,
  Card,
  CardContent,
  Divider,
  Button,
} from "@mui/material";
import Image from "next/image";
import Link from "next/link";

export default function TermsOfService() {
  return (
    <main
      style={{
        background: "linear-gradient(to right, #e3f2fd, #bbdefb, #90caf9)",
        paddingBottom: "2rem",
      }}
    >
      <Container maxWidth="lg" sx={{ py: 4 }}>
        <Box display="flex" justifyContent="center" mb={4}>
          <Image
            src="/Logo_Withtext.png"
            width={300}
            height={300}
            alt="SalaryApp Logo"
          />
        </Box>
        <Card sx={{ p: { xs: 3, sm: 5 }, borderRadius: 4, boxShadow: 6 }}>
          <CardContent>
            <Typography
              variant="h4"
              component="h1"
              sx={{ fontWeight: "bold", mb: 2 }}
            >
              Terms of Service
            </Typography>
            <Divider sx={{ mb: 3 }} />
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              Welcome to SalaryApp! These Terms of Service ("Terms") govern your
              use of the SalaryApp platform and its services. By using or
              accessing SalaryApp, you agree to comply with and be bound by
              these Terms. If you do not agree to these Terms, you must refrain
              from using our services.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              1. Acceptance of Terms
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              By accessing or using SalaryApp, you accept and agree to be bound
              by these Terms. If you are using the platform on behalf of an
              organization, you confirm that you have the authority to bind that
              organization to these Terms.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              2. User Responsibilities
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              As a user, you agree to:
            </Typography>
            <ul>
              <li>
                Provide accurate and complete information when using SalaryApp.
              </li>
              <li>
                Ensure that all data entered into the platform is correct and
                up-to-date.
              </li>
              <li>
                Verify the accuracy of any reports, documents, or outputs
                generated by SalaryApp.
              </li>
              <li>
                Maintain the confidentiality of your login credentials and
                prevent unauthorized access to your account.
              </li>
              <li>
                Comply with all applicable laws and regulations related to data
                privacy and security.
              </li>
              <li>
                Ensure that any data entered into SalaryApp is not fraudulent or
                misleading.
              </li>
            </ul>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              3. Admin Rights and User Termination
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              Administrators have the authority to manage and oversee the use of
              SalaryApp. In the event of a violation of these Terms or any
              suspicious or illegal activity, administrators reserve the right
              to suspend or terminate the account of any user or registered
              company. This action may be taken without notice and could result
              in the permanent removal of the user's access to the platform.
              Users will be solely responsible for any damages resulting from
              the termination of their account or the account of any other user
              under their control.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              4. Employer Responsibilities
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              Employers, or authorized representatives of companies, have the
              responsibility to:
            </Typography>
            <ul>
              <li>
                Ensure the accuracy and legality of any data entered into
                SalaryApp.
              </li>
              <li>
                Verify the correctness of any reports or documents generated by
                the platform.
              </li>
              <li>
                Ensure that only authorized individuals are using SalaryApp on
                behalf of the company.
              </li>
              <li>
                Comply with all applicable laws related to data protection and
                employee rights.
              </li>
              <li>
                Manage and secure sensitive information entered into SalaryApp
                in accordance with privacy policies and regulations.
              </li>
            </ul>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              5. Use Restrictions
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              You agree that SalaryApp and its services are solely for the use
              of employers or responsible individuals within registered
              companies. The use of SalaryApp for any unauthorized purposes,
              including resale or distribution of the platform's outputs for
              commercial gain, is strictly prohibited. You may not sell, rent,
              or lease the services or outputs generated by SalaryApp to third
              parties. Only employers or authorized representatives of a company
              may use the platform for its intended purposes.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              6. Privacy and Data Protection
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              SalaryApp takes data privacy seriously. Please refer to our
              Privacy Policy to understand how we collect, use, and protect your
              data. By using SalaryApp, you agree to our data practices as
              outlined in the Privacy Policy.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              7. Disclaimer of Warranties
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              SalaryApp is provided "as is" without any warranties or
              representations, express or implied. We do not guarantee the
              availability, accuracy, or reliability of the platform or its
              outputs. You use SalaryApp at your own risk and agree that
              SalaryApp will not be liable for any errors, omissions, or
              inaccuracies in the data or reports provided.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              8. Limitation of Liability
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              To the fullest extent permitted by law, SalaryApp, its affiliates,
              and employees will not be liable for any indirect, incidental,
              special, or consequential damages arising out of or in connection
              with your use of the platform, including, but not limited to, loss
              of data, profits, or business opportunities.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              9. Termination
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              We reserve the right to suspend or terminate your access to
              SalaryApp at any time, without notice, for any reason, including
              violation of these Terms or illegal conduct. Upon termination,
              your access to SalaryApp will be revoked, and you must immediately
              cease using the platform.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              10. Updates to These Terms
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              We may update these Terms from time to time to reflect changes in
              our practices or for other operational, legal, or regulatory
              reasons. Any changes will be communicated through the application
              or via email, and the revised Terms will be posted on this page
              with an updated effective date.
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              By continuing to use SalaryApp after any changes to these Terms,
              you agree to the updated Terms. If you do not agree with the
              changes, you must stop using SalaryApp immediately.
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              If you have any questions or concerns regarding these Terms,
              please contact us at our support channels.
            </Typography>
          </CardContent>
        </Card>
        <Box display="flex" justifyContent="center" mt={4}>
          <Link href="/">
            <Button variant="contained" color="primary" sx={{ my: 1 }}>
              Go Back to Home
            </Button>
          </Link>
        </Box>
      </Container>
    </main>
  );
}
