import {
  Container,
  Box,
  Card,
  CardContent,
  Typography,
  Divider,
} from "@mui/material";
import Image from "next/image";
import React from "react";

const Agreement = () => {
  return (
    <>
      <Box display="flex" justifyContent="center" mb={4}>
        <Image
          src="/Logo_Withtext.png"
          width={300}
          height={300}
          alt="SalaryApp Logo"
        />
      </Box>
      <Card sx={{ p: { xs: 1, sm: 5 }, borderRadius: 4, boxShadow: 6 }}>
        <CardContent>
          <Typography
            variant="h4"
            component="h1"
            sx={{ fontWeight: "bold", mb: 2 }}
          >
            User Agreement
          </Typography>
          <Divider sx={{ mb: 3 }} />
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            Welcome to SalaryApp! This User Agreement (&quot;Agreement&quot;)
            sets forth the terms and conditions under which you are allowed to
            use the SalaryApp platform and services. By registering or using
            SalaryApp, you agree to be bound by the terms outlined below.
          </Typography>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            1. Acceptance of Agreement
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            By using SalaryApp, you confirm that you have read, understood, and
            agree to comply with this Agreement and any associated policies. If
            you do not agree with the terms of this Agreement, you must not use
            the platform.
          </Typography>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            2. Eligibility and Registration
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            To use SalaryApp, you must be an authorized representative of a
            company or an employer who is responsible for managing the
            company&apos;s employee records. When registering for the platform,
            you agree to provide accurate, complete, and up-to-date information.
          </Typography>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            3. User Responsibilities
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            As a user of SalaryApp, you are responsible for:
          </Typography>
          <ul>
            <li>
              Providing accurate and truthful information when registering or
              using the platform.
            </li>
            <li>
              Ensuring that all data entered into the system is accurate and
              up-to-date.
            </li>
            <li>
              Verifying the outputs generated by SalaryApp, including reports
              and documents.
            </li>
            <li>
              Managing and protecting the confidentiality of your account and
              login credentials.
            </li>
            <li>
              Not using SalaryApp for any unauthorized commercial purposes,
              including resale of outputs or generating profit from the
              platform’s services.
            </li>
          </ul>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            4. Platform Access
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            SalaryApp provides you with access to its platform and services for
            the purpose of managing company data, employee records, salary
            management, and related functionalities. Your access to the platform
            is provided on a non-exclusive, non-transferable basis, and you are
            granted a limited, revocable right to use the platform as outlined
            in this Agreement.
          </Typography>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            5. Prohibited Uses
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            You may not use SalaryApp for any purpose other than its intended
            use, including, but not limited to:
          </Typography>
          <ul>
            <li>
              Reselling, distributing, or licensing any of the outputs generated
              by SalaryApp.
            </li>
            <li>
              Using the platform to engage in fraudulent or illegal activities.
            </li>
            <li>
              Sharing your login credentials with unauthorized individuals.
            </li>
            <li>
              Attempting to modify, reverse-engineer, or tamper with the
              platform’s functionalities or security features.
            </li>
          </ul>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            6. Data Privacy and Security
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            By using SalaryApp, you agree to our Privacy Policy, which governs
            the collection, use, and protection of your personal and company
            data. We implement appropriate security measures to protect your
            data from unauthorized access or disclosure, but cannot guarantee
            absolute security.
          </Typography>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            7. Termination of Access
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            SalaryApp reserves the right to suspend or terminate your account or
            access to the platform if you violate any of the terms of this
            Agreement. This includes, but is not limited to, misuse of the
            platform, fraudulent activity, or non-compliance with applicable
            laws and regulations. Upon termination, your access to SalaryApp
            will be revoked, and you must immediately cease using the platform.
          </Typography>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            8. Liability and Disclaimers
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            SalaryApp is provided &quot;as is&quot; without any warranties or
            representations, either express or implied. We do not guarantee the
            availability, accuracy, or reliability of the platform. In no event
            will SalaryApp or its affiliates be liable for any direct, indirect,
            incidental, or consequential damages arising from your use of the
            platform.
          </Typography>

          <Typography
            variant="h5"
            component="h2"
            sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
          >
            9. Updates to the Agreement
          </Typography>
          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            We may update this User Agreement from time to time. Any changes
            will be posted on this page, and the effective date of the changes
            will be updated accordingly. By continuing to use SalaryApp after
            the changes, you agree to the updated Agreement.
          </Typography>

          <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
            If you have any questions or concerns regarding this Agreement,
            please contact us at our support channels.
          </Typography>
        </CardContent>
      </Card>
    </>
  );
};

export default Agreement;
