import {
  Box,
  Typography,
  Container,
  Card,
  CardContent,
  Divider,
} from "@mui/material";
import Image from "next/image";

export default function PrivacyPolicy() {
  return (
    <main
      style={{
        background: "linear-gradient(to right, #e3f2fd, #bbdefb, #90caf9)",
        paddingBottom: "2rem",
      }}
    >
      <Container maxWidth="lg" sx={{ py: 4 }}>
        <Box display="flex" justifyContent="center" mb={4}>
          <Image
            src="/Logo_Withtext.png"
            width={300}
            height={300}
            alt="SalaryApp Logo"
          />
        </Box>
        <Card sx={{ p: { xs: 3, sm: 5 }, borderRadius: 4, boxShadow: 6 }}>
          <CardContent>
            <Typography
              variant="h4"
              component="h1"
              sx={{ fontWeight: "bold", mb: 2 }}
            >
              Privacy Policy
            </Typography>
            <Divider sx={{ mb: 3 }} />
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              Welcome to SalaryApp! This Privacy Policy outlines how we handle
              your data, our commitments to security, and the responsibilities
              that employers and administrators have while using our
              application. By using SalaryApp, you agree to the terms outlined
              in this policy.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              Employer Responsibilities
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              As an employer, you are responsible for entering and managing all
              data related to your company and employees within SalaryApp. This
              includes, but is not limited to, employee personal information,
              salary details, leave records, and any other data you choose to
              store in the system. It is imperative that the information you
              enter is accurate and up to date, as SalaryApp cannot verify the
              correctness of data entered by users.
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              Furthermore, you are responsible for ensuring that any outputs
              generated by the application—such as salary reports, tax
              calculations, and EPF/ETF statements—are accurate and comply with
              relevant regulations. SalaryApp serves as a tool to assist with
              these tasks, but it is up to you to verify the validity of all
              documents before using them in a business or legal context.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              Admin Access
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              Administrators within SalaryApp have access to the data of all
              users within the application. This allows them to monitor and
              manage the platform’s usage, ensuring that data is handled
              responsibly and in compliance with the platform’s terms of
              service. While administrators can view user and company data, rest
              assured that sensitive information, such as passwords, is
              encrypted and remains secure at all times.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              Data Security and Privacy
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              At SalaryApp, we are committed to ensuring the security and
              privacy of your data. While passwords are encrypted using strong
              encryption algorithms, other data—such as company details,
              employee records, and salary information—is stored securely but is
              not encrypted at rest. We take all reasonable measures to protect
              your data from unauthorized access, disclosure, alteration, and
              destruction.
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              However, it is important to note that the security of your data
              also depends on how you manage it. Employers and administrators
              are encouraged to implement strong internal policies to safeguard
              sensitive employee data, including using secure access methods and
              regularly reviewing the information stored in the platform.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              Data Retention and Deletion
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              SalaryApp retains your data for as long as you continue to use the
              platform or as required by law. If you choose to delete your
              account or stop using SalaryApp, we will retain your data for a
              reasonable period before it is fully deleted. Please note that
              some data may be retained for legal or compliance reasons, but no
              personal information will be shared without your consent.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              Disclaimer of Liability
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              SalaryApp is designed as a tool to assist with salary management,
              EPF/ETF contributions, and employee records. While we strive to
              provide accurate and useful features, we do not take
              responsibility for the accuracy of any data entered or the outputs
              generated by the application. It is the employer’s responsibility
              to verify the data and ensure that all legal and regulatory
              requirements are met before using any generated documents or
              reports for official purposes.
            </Typography>
            <Typography
              variant="h5"
              component="h2"
              sx={{ fontWeight: "bold", mt: 3, mb: 2 }}
            >
              Updates to This Policy
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              We may update this Privacy Policy from time to time to reflect
              changes in our practices or for other operational, legal, or
              regulatory reasons. Any changes will be communicated through the
              application or via email, and the revised policy will be posted on
              this page with an updated effective date.
            </Typography>
            <Typography variant="body1" paragraph sx={{ lineHeight: 1.8 }}>
              By using SalaryApp, you acknowledge and agree to the terms
              outlined in this Privacy Policy. If you have any questions or
              concerns, please contact us at our support channels.
            </Typography>
          </CardContent>
        </Card>
      </Container>
    </main>
  );
}
